#Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
#By starting with 1 and 2, the first 10 terms will be:
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


a,b =1,2
max = 600
sum=0
print(a, b, end = ' ')
while b < max:
	a, b = b, a + b
	print(b, end = ' ')

print(" ")
a,b =1,2
sum = 2
while b < max:
	a, b = b, a + b
	if not (b % 2):
		sum +=b
		print(sum, end = ' ')